### ISSUE TITLE
store submit button and page navigation events with timestamps with mongodb

### ISSUE THREAD

**Issue by ybergner** [collabassess/CPSXblock#5]
page navigation is not actually stored yet.

**Comment by ybergner** [comment]
also, there seems to be an issue with which submit button is pressed. For example on problem 008DE if I submit the value, my partner gets a hint result.

**Comment by AjayThorve** [comment]
submit button issue resolved

**Comment by AjayThorve** [comment]
page navigation now stored in mlab
